### ISSUE TITLE
Docker Image does not support RTX 5080

### ISSUE THREAD

**Issue by exotic123567** [Zyphra/Zonos#165]
When I run the commands git clone, cd and docker compose up in my Ubuntu WSL environment I see that the current Pytorch version doesn't support sm_120 capabilities, thus not utilizing my RTX 5080 GPU at all.

I am seeing this : 
`/opt/conda/lib/python3.11/site-packages/torch/cuda/__init__.py:235: UserWarning:
zonos_container  | NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
zonos_container  | The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
zonos_container  | If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/`

**Comment by Wontfallo** [comment]
Haha! For having a 5080

**Comment by Filipus24** [comment]
@Wontfallo, well you'll find this hilarious then: I have a similar issue with my Radeon RX 6750. It's probably related to CUDA: 
_nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown_

Now I ran into a similar issue while installing a local instance of Fooocus, but was able to make it work with the ROCm fix for Windows. I'm wondering if the same kind of fix could be integrated in this container (or perhaps in a different container that's AMD-specific).

**Comment by Wontfallo** [comment]
Haha! For having a 5080.

Tongue-in-cheek, boys, I was being facetious. Poking fun because most of the world, despite waiting in lines and refreshing online carts, can't get their hands on a 5000-series GPU.
I was teasing, not laughing at his misfortune...well I kind of am. Only because of my envy

**Comment by Wontfallo** [comment]
> [@Wontfallo](https://github.com/Wontfallo), well you'll find this hilarious then: I have a similar issue with my Radeon RX 6750. It's probably related to CUDA: _nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown_
> 
> Now I ran into a similar issue while installing a local instance of Fooocus, but was able to make it work with the ROCm fix for Windows. I'm wondering if the same kind of fix could be integrated in this container (or perhaps in a different container that's AMD-specific).

It a tough world out there for team red, especially since most of it runs on CUDA.  
That sucks though I wish there was a universal abstraction layer that could sit closer to the hardware that everyone could utilize instead of one company creating a 'standard'

**Comment by codeuh** [comment]
@exotic123567 Currently you have to use a nightly build version of pytorch for 5000 series compatibility. I found a comment on another text-to-speech solution's similar issue that mentioned this and followed that person's recommendation to get this working on my 5090. I'm not using docker compose but I was able to get this running on my RHEL 9 WSL2 distro with uv directly by taking the below solution and applying it here.

https://github.com/nari-labs/dia/issues/26#issuecomment-2828484601

Here's my modified pyproject.toml that's working for me on my 5000 series card using a pinned nightly build version from 2025 04 09 of the required pytorch components.

````toml
[project]
name = "zonos"
version = "0.1.0"
description = "Text-to-speech by Zyphra"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch==2.8.0.dev20250409+cu128; platform_system != 'Darwin'",
    "setuptools",
    "packaging",
    "inflect>=7.5.0",
    "kanjize>=1.5.0",
    "numpy>=2.2.2",
    "phonemizer>=3.3.0",
    "sudachidict-full>=20241021",
    "sudachipy>=0.6.10",
    "torchaudio==2.6.0.dev20250409+cu128; platform_system != 'Darwin'",
    "pytorch-triton==3.3.0+git96316ce5; platform_system != 'Darwin'",
    "transformers>=4.48.1",
    "soundfile>=0.13.1",
    "huggingface-hub>=0.28.1",
    "gradio>=5.15.0",
]

# These are technically optional, but mamba-ssm is required to run hybrid models.
[project.optional-dependencies]
compile = [
    "flash-attn>=2.7.3",
    "mamba-ssm>=2.2.4",
    "causal-conv1d>=1.5.0.post8",
]

[tool.setuptools.packages.find]
include = ["zonos"]

[tool.uv.sources]
torch = { index = "pytorch", marker = "platform_system != 'Darwin'" }
torchaudio = { index = "pytorch", marker = "platform_system != 'Darwin'" }
pytorch-triton = { index = "pytorch", marker = "platform_system != 'Darwin'" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/nightly/cu128"
explicit = true

[tool.uv]
no-build-isolation-package = ["flash-attn", "mamba-ssm", "causal-conv1d"]

[tool.ruff]
line-length = 120
````
