### ISSUE TITLE
Zonos doesn't work on Blackwell cards (RTX 50)

### ISSUE THREAD

**Issue by rogsme** [Zyphra/Zonos#178]
I followed the instructions to run locally:

```
 uv sync
 uv sync --extra compile
 uv pip install -e .
```
And everything worked perfectly. 

But when I run `uv run sample.py`, I get the following error:
```
/opt/zonos/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:235: UserWarning:
NVIDIA Graphics Device with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA Graphics Device GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
Traceback (most recent call last):
  File "/opt/zonos/sample.py", line 8, in <module>
    model = Zonos.from_pretrained("Zyphra/Zonos-v0.1-transformer", device=device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zonos/zonos/model.py", line 63, in from_pretrained
    return cls.from_local(config_path, model_path, device, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zonos/zonos/model.py", line 86, in from_local
    model.load_state_dict(sd)
  File "/opt/zonos/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2561, in load_state_dict
    load(self, state_dict)
  File "/opt/zonos/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2554, in load
    out = hook(module, incompatible_keys)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zonos/zonos/model.py", line 51, in _pad_embeddings_and_heads
    pad_weight_(w, self.config.pad_vocab_to_multiple_of)
  File "/opt/zonos/zonos/utils.py", line 24, in pad_weight_
    w.weight.data = F.pad(w.weight.data, (0, 0, 0, w.weight.shape[0] % multiple))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zonos/.venv/lib/python3.12/site-packages/torch/nn/functional.py", line 5209, in pad
    return torch._C._nn.pad(input, pad, mode, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Maybe there's a workaround to make it work on Blackwell cards?

**Comment by darkacorn** [comment]
read up .. its torch .. not zonos - thats what you get for beta-testing an architecture.

**Comment by rogsme** [comment]
> read up .. its torch .. not zonos - thats what you get for beta-testing an architecture.

Ok, I wasn't expecting a passive aggressive response. Thank you anyways, I'll look for a workaround elsewhere (maybe the nightly releases for Torch).

**Comment by darkacorn** [comment]
nothing passive agressive here - but there are quite a few things that are not compatible with blackwell yet - if you adopt early that's to be expected

**Comment by sudolink** [comment]
torchaudio not updated yet it seems

**Comment by loscrossos** [comment]
sadly  @darkacorn is right. for 50xx to work you need a torch/Taudio compiled with 12.8.
Also you need triton at least 3.3.

the 50 series cuda cards came out but driver support is not fully there. on linux it is just starting to get well. Ubuntu LTS does not support them out of the box and CUDA only in the latest version. CUDA is usually backwards compatible.

**Comment by mikecolu** [comment]
This is now working with torch/torchaudio-2.7.0+cu128-cp310
And torchvision-0.22.0+cu128-cp310

Do note that i also installed flash-attn-2.7.4.post1+cu128torch2.7.0

**Comment by k95555** [comment]
Upgrading to the RTX 5080 was my big mistake. I had the 3080, and everything was working perfectly fine. So many AI tools I tried, such as RVC, Zonos, and AudioX, do not work anymore on the 5080, just because of PyTorch. It might work, but it’s going to take days of work time, which I cannot spare at the moment. I have already wasted a whole week. If I had known NVIDIA changed the architecture in the 50 series, which would cause PyTorch incompatibility, I would have never bought it.

**Comment by loscrossos** [comment]
check my account. all the projects on it are blackwell optimized. feel free to propose new projects.


also i have a project to enable projects on blackwell
